#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v27
# autospec commit: 6aaa12f
#
Name     : NetworkManager
Version  : 1.50.0
Release  : 104
URL      : https://download.gnome.org/sources/NetworkManager/1.50/NetworkManager-1.50.0.tar.xz
Source0  : https://download.gnome.org/sources/NetworkManager/1.50/NetworkManager-1.50.0.tar.xz
Summary  : Network connection manager and user applications
Group    : Development/Tools
License  : GFDL-1.1 GPL-2.0 GPL-2.0+ LGPL-2.1 LGPL-2.1+
Requires: NetworkManager-autostart = %{version}-%{release}
Requires: NetworkManager-bin = %{version}-%{release}
Requires: NetworkManager-config = %{version}-%{release}
Requires: NetworkManager-data = %{version}-%{release}
Requires: NetworkManager-lib = %{version}-%{release}
Requires: NetworkManager-libexec = %{version}-%{release}
Requires: NetworkManager-license = %{version}-%{release}
Requires: NetworkManager-locales = %{version}-%{release}
Requires: NetworkManager-services = %{version}-%{release}
Requires: ppp
BuildRequires : ModemManager-dev
BuildRequires : bluez-dev
BuildRequires : buildreq-gnome
BuildRequires : buildreq-kde
BuildRequires : buildreq-meson
BuildRequires : curl-dev
BuildRequires : dbus-dev
BuildRequires : dbus-glib-dev
BuildRequires : gobject-introspection-dev
BuildRequires : iptables
BuildRequires : iptables-dev
BuildRequires : jansson-dev
BuildRequires : libndp-dev
BuildRequires : libnl-dev
BuildRequires : libsoup-dev
BuildRequires : linux-firmware-wifi
BuildRequires : mobile-broadband-provider-info
BuildRequires : ncurses-dev
BuildRequires : newt-dev
BuildRequires : nss-dev
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(mobile-broadband-provider-info)
BuildRequires : pkgconfig(polkit-gobject-1)
BuildRequires : polkit-dev
BuildRequires : ppp-dev
BuildRequires : pygobject
BuildRequires : readline-dev
BuildRequires : systemd-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Add-clr-all-ifs-option.patch

%description
NetworkManager is a system service that manages network interfaces and
connections based on user or automatic configuration. It supports
Ethernet, Bridge, Bond, VLAN, Team, InfiniBand, Wi-Fi, mobile broadband
(WWAN), PPPoE and other devices, and supports a variety of different VPN
services.

%package autostart
Summary: autostart components for the NetworkManager package.
Group: Default

%description autostart
autostart components for the NetworkManager package.


%package bin
Summary: bin components for the NetworkManager package.
Group: Binaries
Requires: NetworkManager-data = %{version}-%{release}
Requires: NetworkManager-libexec = %{version}-%{release}
Requires: NetworkManager-config = %{version}-%{release}
Requires: NetworkManager-license = %{version}-%{release}
Requires: NetworkManager-services = %{version}-%{release}

%description bin
bin components for the NetworkManager package.


%package config
Summary: config components for the NetworkManager package.
Group: Default

%description config
config components for the NetworkManager package.


%package data
Summary: data components for the NetworkManager package.
Group: Data

%description data
data components for the NetworkManager package.


%package dev
Summary: dev components for the NetworkManager package.
Group: Development
Requires: NetworkManager-lib = %{version}-%{release}
Requires: NetworkManager-bin = %{version}-%{release}
Requires: NetworkManager-data = %{version}-%{release}
Provides: NetworkManager-devel = %{version}-%{release}
Requires: NetworkManager = %{version}-%{release}

%description dev
dev components for the NetworkManager package.


%package doc
Summary: doc components for the NetworkManager package.
Group: Documentation

%description doc
doc components for the NetworkManager package.


%package extras
Summary: extras components for the NetworkManager package.
Group: Default
Requires: ModemManager
Requires: NetworkManager
Requires: NetworkManager-l2tp
Requires: NetworkManager-openconnect
Requires: NetworkManager-openvpn
Requires: NetworkManager-vpnc
Requires: libreswan
Requires: linux-firmware-wifi
Requires: network-manager-applet
Requires: usb-modeswitch
Requires: usb-modeswitch-data
Requires: xl2tpd

%description extras
extras components for the NetworkManager package.


%package lib
Summary: lib components for the NetworkManager package.
Group: Libraries
Requires: NetworkManager-data = %{version}-%{release}
Requires: NetworkManager-libexec = %{version}-%{release}
Requires: NetworkManager-license = %{version}-%{release}

%description lib
lib components for the NetworkManager package.


%package libexec
Summary: libexec components for the NetworkManager package.
Group: Default
Requires: NetworkManager-config = %{version}-%{release}
Requires: NetworkManager-license = %{version}-%{release}

%description libexec
libexec components for the NetworkManager package.


%package license
Summary: license components for the NetworkManager package.
Group: Default

%description license
license components for the NetworkManager package.


%package locales
Summary: locales components for the NetworkManager package.
Group: Default

%description locales
locales components for the NetworkManager package.


%package services
Summary: services components for the NetworkManager package.
Group: Systemd services
Requires: /usr/bin/busctl
Requires: systemd

%description services
services components for the NetworkManager package.


%prep
%setup -q -n NetworkManager-1.50.0
cd %{_builddir}/NetworkManager-1.50.0
%patch -P 1 -p1
pushd ..
cp -a NetworkManager-1.50.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1749240815
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dconfig_plugins_default=keyfile \
-Dconfig_dhcp_default=dhclient \
-Ddhclient=/usr/libexec/dhclient \
-Dsuspend_resume=systemd \
-Dconfig_logging_backend_default=journal \
-Dmodify_system=true \
-Dkernel_firmware_dir=/usr/lib/firmware \
-Ddbus_conf_dir=/usr/share/dbus-1/system.d \
-Dbluez5_dun=true \
-Dsystem_ca_path=/var/cache/ca-certs/anchors \
-Diptables=/usr/bin/iptables \
-Dovs=false \
-Diwd=true \
-Dselinux=false \
-Dlibaudit=no \
-Dqt=false  builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dconfig_plugins_default=keyfile \
-Dconfig_dhcp_default=dhclient \
-Ddhclient=/usr/libexec/dhclient \
-Dsuspend_resume=systemd \
-Dconfig_logging_backend_default=journal \
-Dmodify_system=true \
-Dkernel_firmware_dir=/usr/lib/firmware \
-Ddbus_conf_dir=/usr/share/dbus-1/system.d \
-Dbluez5_dun=true \
-Dsystem_ca_path=/var/cache/ca-certs/anchors \
-Diptables=/usr/bin/iptables \
-Dovs=false \
-Diwd=true \
-Dselinux=false \
-Dlibaudit=no \
-Dqt=false  builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/NetworkManager
cp %{_builddir}/NetworkManager-%{version}/COPYING %{buildroot}/usr/share/package-licenses/NetworkManager/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/NetworkManager-%{version}/COPYING.GFDL %{buildroot}/usr/share/package-licenses/NetworkManager/7205ad2e7451e9c4a518d105d5144987cdaf9bfa || :
cp %{_builddir}/NetworkManager-%{version}/COPYING.LGPL %{buildroot}/usr/share/package-licenses/NetworkManager/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang NetworkManager
## Remove excluded files
rm -f %{buildroot}*/usr/lib/udev/rules.d/84-nm-drivers.rules
## install_append content
# Ensure dbus activation will work without requiring enable at boot
pushd %{buildroot}/usr/lib/systemd/system
ln -s NetworkManager.service dbus-org.freedesktop.NetworkManager.service
ln -s NetworkManager-dispatcher.service dbus-org.freedesktop.nm-dispatcher.service
popd
mkdir -p %{buildroot}/usr/lib/systemd/system/multi-user.target.wants
pushd %{buildroot}/usr/lib/systemd/system/multi-user.target.wants
ln -sf ../NetworkManager.service NetworkManager.service
popd
mkdir -p %{buildroot}/usr/lib/systemd/system/network-online.target.wants
pushd %{buildroot}/usr/lib/systemd/system/network-online.target.wants
ln -sf ../NetworkManager-wait-online.service NetworkManager-wait-online.service
popd
mv %{buildroot}/usr/sbin/NetworkManager %{buildroot}/usr/bin/NetworkManager
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib/NetworkManager/dispatcher.d/90-nm-cloud-setup.sh
/usr/lib/NetworkManager/dispatcher.d/no-wait.d/90-nm-cloud-setup.sh
/usr/lib/NetworkManager/dispatcher.d/pre-up.d/90-nm-cloud-setup.sh
/usr/lib/firewalld/zones/nm-shared.xml

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/NetworkManager.service
/usr/lib/systemd/system/network-online.target.wants/NetworkManager-wait-online.service

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/NetworkManager
/V3/usr/bin/nm-online
/V3/usr/bin/nmcli
/usr/bin/NetworkManager
/usr/bin/nm-online
/usr/bin/nmcli

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/85-nm-unmanaged.rules
/usr/lib/udev/rules.d/90-nm-thunderbolt.rules

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/NM-1.0.typelib
/usr/share/bash-completion/completions/nmcli
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.AccessPoint.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.AgentManager.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Checkpoint.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Connection.Active.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.DHCP4Config.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.DHCP6Config.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Adsl.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Bluetooth.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Bond.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Bridge.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Dummy.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Generic.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Hsr.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.IPTunnel.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Infiniband.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Loopback.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Lowpan.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Macsec.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Macvlan.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Modem.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.OlpcMesh.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.OvsBridge.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.OvsInterface.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.OvsPort.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Ppp.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Statistics.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Team.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Tun.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Veth.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Vlan.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Vrf.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Vxlan.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.WiMax.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.WifiP2P.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.WireGuard.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Wired.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Wireless.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.Wpan.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Device.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.DnsManager.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.IP4Config.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.IP6Config.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.PPP.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.SecretAgent.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Settings.Connection.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.Settings.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.VPN.Connection.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.VPN.Plugin.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.WiMax.Nsp.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.WifiP2PPeer.xml
/usr/share/dbus-1/interfaces/org.freedesktop.NetworkManager.xml
/usr/share/dbus-1/system-services/org.freedesktop.nm_dispatcher.service
/usr/share/dbus-1/system-services/org.freedesktop.nm_priv_helper.service
/usr/share/dbus-1/system.d/nm-dispatcher.conf
/usr/share/dbus-1/system.d/nm-priv-helper.conf
/usr/share/dbus-1/system.d/org.freedesktop.NetworkManager.conf
/usr/share/gir-1.0/*.gir
/usr/share/polkit-1/actions/org.freedesktop.NetworkManager.policy
/usr/share/vala/vapi/libnm.deps
/usr/share/vala/vapi/libnm.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/libnm/NetworkManager.h
/usr/include/libnm/nm-access-point.h
/usr/include/libnm/nm-active-connection.h
/usr/include/libnm/nm-autoptr.h
/usr/include/libnm/nm-checkpoint.h
/usr/include/libnm/nm-client.h
/usr/include/libnm/nm-conn-utils.h
/usr/include/libnm/nm-connection.h
/usr/include/libnm/nm-core-enum-types.h
/usr/include/libnm/nm-core-types.h
/usr/include/libnm/nm-dbus-interface.h
/usr/include/libnm/nm-device-6lowpan.h
/usr/include/libnm/nm-device-adsl.h
/usr/include/libnm/nm-device-bond.h
/usr/include/libnm/nm-device-bridge.h
/usr/include/libnm/nm-device-bt.h
/usr/include/libnm/nm-device-dummy.h
/usr/include/libnm/nm-device-ethernet.h
/usr/include/libnm/nm-device-generic.h
/usr/include/libnm/nm-device-hsr.h
/usr/include/libnm/nm-device-infiniband.h
/usr/include/libnm/nm-device-ip-tunnel.h
/usr/include/libnm/nm-device-loopback.h
/usr/include/libnm/nm-device-macsec.h
/usr/include/libnm/nm-device-macvlan.h
/usr/include/libnm/nm-device-modem.h
/usr/include/libnm/nm-device-olpc-mesh.h
/usr/include/libnm/nm-device-ovs-bridge.h
/usr/include/libnm/nm-device-ovs-interface.h
/usr/include/libnm/nm-device-ovs-port.h
/usr/include/libnm/nm-device-ppp.h
/usr/include/libnm/nm-device-team.h
/usr/include/libnm/nm-device-tun.h
/usr/include/libnm/nm-device-veth.h
/usr/include/libnm/nm-device-vlan.h
/usr/include/libnm/nm-device-vrf.h
/usr/include/libnm/nm-device-vxlan.h
/usr/include/libnm/nm-device-wifi-p2p.h
/usr/include/libnm/nm-device-wifi.h
/usr/include/libnm/nm-device-wimax.h
/usr/include/libnm/nm-device-wireguard.h
/usr/include/libnm/nm-device-wpan.h
/usr/include/libnm/nm-device.h
/usr/include/libnm/nm-dhcp-config.h
/usr/include/libnm/nm-enum-types.h
/usr/include/libnm/nm-errors.h
/usr/include/libnm/nm-ethtool-utils.h
/usr/include/libnm/nm-ip-config.h
/usr/include/libnm/nm-keyfile.h
/usr/include/libnm/nm-object.h
/usr/include/libnm/nm-remote-connection.h
/usr/include/libnm/nm-secret-agent-old.h
/usr/include/libnm/nm-setting-6lowpan.h
/usr/include/libnm/nm-setting-8021x.h
/usr/include/libnm/nm-setting-adsl.h
/usr/include/libnm/nm-setting-bluetooth.h
/usr/include/libnm/nm-setting-bond-port.h
/usr/include/libnm/nm-setting-bond.h
/usr/include/libnm/nm-setting-bridge-port.h
/usr/include/libnm/nm-setting-bridge.h
/usr/include/libnm/nm-setting-cdma.h
/usr/include/libnm/nm-setting-connection.h
/usr/include/libnm/nm-setting-dcb.h
/usr/include/libnm/nm-setting-dummy.h
/usr/include/libnm/nm-setting-ethtool.h
/usr/include/libnm/nm-setting-generic.h
/usr/include/libnm/nm-setting-gsm.h
/usr/include/libnm/nm-setting-hostname.h
/usr/include/libnm/nm-setting-hsr.h
/usr/include/libnm/nm-setting-infiniband.h
/usr/include/libnm/nm-setting-ip-config.h
/usr/include/libnm/nm-setting-ip-tunnel.h
/usr/include/libnm/nm-setting-ip4-config.h
/usr/include/libnm/nm-setting-ip6-config.h
/usr/include/libnm/nm-setting-link.h
/usr/include/libnm/nm-setting-loopback.h
/usr/include/libnm/nm-setting-macsec.h
/usr/include/libnm/nm-setting-macvlan.h
/usr/include/libnm/nm-setting-match.h
/usr/include/libnm/nm-setting-olpc-mesh.h
/usr/include/libnm/nm-setting-ovs-bridge.h
/usr/include/libnm/nm-setting-ovs-dpdk.h
/usr/include/libnm/nm-setting-ovs-external-ids.h
/usr/include/libnm/nm-setting-ovs-interface.h
/usr/include/libnm/nm-setting-ovs-other-config.h
/usr/include/libnm/nm-setting-ovs-patch.h
/usr/include/libnm/nm-setting-ovs-port.h
/usr/include/libnm/nm-setting-ppp.h
/usr/include/libnm/nm-setting-pppoe.h
/usr/include/libnm/nm-setting-proxy.h
/usr/include/libnm/nm-setting-serial.h
/usr/include/libnm/nm-setting-sriov.h
/usr/include/libnm/nm-setting-tc-config.h
/usr/include/libnm/nm-setting-team-port.h
/usr/include/libnm/nm-setting-team.h
/usr/include/libnm/nm-setting-tun.h
/usr/include/libnm/nm-setting-user.h
/usr/include/libnm/nm-setting-veth.h
/usr/include/libnm/nm-setting-vlan.h
/usr/include/libnm/nm-setting-vpn.h
/usr/include/libnm/nm-setting-vrf.h
/usr/include/libnm/nm-setting-vxlan.h
/usr/include/libnm/nm-setting-wifi-p2p.h
/usr/include/libnm/nm-setting-wimax.h
/usr/include/libnm/nm-setting-wired.h
/usr/include/libnm/nm-setting-wireguard.h
/usr/include/libnm/nm-setting-wireless-security.h
/usr/include/libnm/nm-setting-wireless.h
/usr/include/libnm/nm-setting-wpan.h
/usr/include/libnm/nm-setting.h
/usr/include/libnm/nm-simple-connection.h
/usr/include/libnm/nm-utils.h
/usr/include/libnm/nm-version-macros.h
/usr/include/libnm/nm-version.h
/usr/include/libnm/nm-vpn-connection.h
/usr/include/libnm/nm-vpn-dbus-interface.h
/usr/include/libnm/nm-vpn-editor-plugin.h
/usr/include/libnm/nm-vpn-editor.h
/usr/include/libnm/nm-vpn-plugin-info.h
/usr/include/libnm/nm-vpn-plugin-old.h
/usr/include/libnm/nm-vpn-service-plugin.h
/usr/include/libnm/nm-wifi-p2p-peer.h
/usr/include/libnm/nm-wimax-nsp.h
/usr/lib64/libnm.so
/usr/lib64/pkgconfig/libnm.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/NetworkManager/*

%files extras
%defattr(-,root,root,-)
/V3/usr/bin/nmtui
/usr/bin/nmtui
/usr/bin/nmtui-connect
/usr/bin/nmtui-edit
/usr/bin/nmtui-hostname

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/NetworkManager/1.50.0/libnm-device-plugin-adsl.so
/V3/usr/lib64/NetworkManager/1.50.0/libnm-device-plugin-bluetooth.so
/V3/usr/lib64/NetworkManager/1.50.0/libnm-device-plugin-wifi.so
/V3/usr/lib64/NetworkManager/1.50.0/libnm-device-plugin-wwan.so
/V3/usr/lib64/NetworkManager/1.50.0/libnm-ppp-plugin.so
/V3/usr/lib64/NetworkManager/1.50.0/libnm-wwan.so
/V3/usr/lib64/libnm.so.0.1.0
/V3/usr/lib64/pppd/2.5.0/nm-pppd-plugin.so
/usr/lib64/NetworkManager/1.50.0/libnm-device-plugin-adsl.so
/usr/lib64/NetworkManager/1.50.0/libnm-device-plugin-bluetooth.so
/usr/lib64/NetworkManager/1.50.0/libnm-device-plugin-wifi.so
/usr/lib64/NetworkManager/1.50.0/libnm-device-plugin-wwan.so
/usr/lib64/NetworkManager/1.50.0/libnm-ppp-plugin.so
/usr/lib64/NetworkManager/1.50.0/libnm-wwan.so
/usr/lib64/libnm.so.0
/usr/lib64/libnm.so.0.1.0
/usr/lib64/pppd/2.5.0/nm-pppd-plugin.so

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/nm-cloud-setup
/V3/usr/libexec/nm-daemon-helper
/V3/usr/libexec/nm-dhcp-helper
/V3/usr/libexec/nm-dispatcher
/V3/usr/libexec/nm-initrd-generator
/V3/usr/libexec/nm-priv-helper
/usr/libexec/nm-cloud-setup
/usr/libexec/nm-daemon-helper
/usr/libexec/nm-dhcp-helper
/usr/libexec/nm-dispatcher
/usr/libexec/nm-initrd-generator
/usr/libexec/nm-priv-helper

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/NetworkManager/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/NetworkManager/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/NetworkManager/7205ad2e7451e9c4a518d105d5144987cdaf9bfa

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/NetworkManager.service
%exclude /usr/lib/systemd/system/network-online.target.wants/NetworkManager-wait-online.service
/usr/lib/systemd/system/NetworkManager-dispatcher.service
/usr/lib/systemd/system/NetworkManager-wait-online.service
/usr/lib/systemd/system/NetworkManager.service
/usr/lib/systemd/system/dbus-org.freedesktop.NetworkManager.service
/usr/lib/systemd/system/dbus-org.freedesktop.nm-dispatcher.service
/usr/lib/systemd/system/nm-cloud-setup.service
/usr/lib/systemd/system/nm-cloud-setup.timer
/usr/lib/systemd/system/nm-priv-helper.service

%files locales -f NetworkManager.lang
%defattr(-,root,root,-)

