#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : NetworkManager
Version  : 1.4.2
Release  : 4
URL      : https://download.gnome.org/sources/NetworkManager/1.4/NetworkManager-1.4.2.tar.xz
Source0  : https://download.gnome.org/sources/NetworkManager/1.4/NetworkManager-1.4.2.tar.xz
Summary  : System for maintaining active network connection
Group    : Development/Tools
License  : GPL-2.0
Requires: NetworkManager-bin
Requires: NetworkManager-config
Requires: NetworkManager-autostart
Requires: NetworkManager-lib
Requires: NetworkManager-data
Requires: NetworkManager-doc
Requires: NetworkManager-locales
BuildRequires : dbus-dev
BuildRequires : dbus-dev32
BuildRequires : dbus-glib-dev
BuildRequires : dbus-glib-dev32
BuildRequires : docbook-xml
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : gettext
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : iptables
BuildRequires : iptables-dev
BuildRequires : iptables-dev32
BuildRequires : libgudev-dev
BuildRequires : libgudev-dev32
BuildRequires : libndp-dev
BuildRequires : libndp-dev32
BuildRequires : libnl-dev
BuildRequires : libnl-dev32
BuildRequires : libxslt-bin
BuildRequires : ncurses-dev
BuildRequires : ncurses-dev32
BuildRequires : nss-dev
BuildRequires : nss-lib32
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(32dbus-1)
BuildRequires : pkgconfig(32gio-unix-2.0)
BuildRequires : pkgconfig(32libnl-3.0)
BuildRequires : pkgconfig(32libsystemd)
BuildRequires : pkgconfig(32systemd)
BuildRequires : pkgconfig(32uuid)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(libnl-3.0)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(nss)
BuildRequires : pkgconfig(polkit-agent-1)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(uuid)
BuildRequires : readline-dev
Patch1: spoof-online.patch

%description
******************
2008-12-11: NetworkManager core daemon has moved to git.freedesktop.org!

%package autostart
Summary: autostart components for the NetworkManager package.
Group: Default

%description autostart
autostart components for the NetworkManager package.


%package bin
Summary: bin components for the NetworkManager package.
Group: Binaries
Requires: NetworkManager-data
Requires: NetworkManager-config

%description bin
bin components for the NetworkManager package.


%package config
Summary: config components for the NetworkManager package.
Group: Default

%description config
config components for the NetworkManager package.


%package data
Summary: data components for the NetworkManager package.
Group: Data

%description data
data components for the NetworkManager package.


%package dev
Summary: dev components for the NetworkManager package.
Group: Development
Requires: NetworkManager-lib
Requires: NetworkManager-bin
Requires: NetworkManager-data
Provides: NetworkManager-devel

%description dev
dev components for the NetworkManager package.


%package dev32
Summary: dev32 components for the NetworkManager package.
Group: Default
Requires: NetworkManager-lib32
Requires: NetworkManager-bin
Requires: NetworkManager-data
Requires: NetworkManager-dev

%description dev32
dev32 components for the NetworkManager package.


%package doc
Summary: doc components for the NetworkManager package.
Group: Documentation

%description doc
doc components for the NetworkManager package.


%package lib
Summary: lib components for the NetworkManager package.
Group: Libraries
Requires: NetworkManager-data
Requires: NetworkManager-config

%description lib
lib components for the NetworkManager package.


%package lib32
Summary: lib32 components for the NetworkManager package.
Group: Default
Requires: NetworkManager-data
Requires: NetworkManager-config

%description lib32
lib32 components for the NetworkManager package.


%package locales
Summary: locales components for the NetworkManager package.
Group: Default

%description locales
locales components for the NetworkManager package.


%prep
%setup -q -n NetworkManager-1.4.2
%patch1 -p1
pushd ..
cp -a NetworkManager-1.4.2 build32
popd

%build
export LANG=C
export SOURCE_DATE_EPOCH=1483026964
%configure --disable-static --disable-ppp \
--disable-polkit-agent \
--disable-wifi \
--disable-teamdctl \
--without-libsoup \
--with-nmcli=no
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static --disable-ppp \
--disable-polkit-agent \
--disable-wifi \
--disable-teamdctl \
--without-libsoup \
--with-nmcli=no  --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%install
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install
%find_lang NetworkManager

%files
%defattr(-,root,root,-)
%exclude /usr/lib32/NetworkManager/libnm-device-plugin-adsl.so
%exclude /usr/lib32/NetworkManager/libnm-settings-plugin-ibft.so
%exclude /usr/lib32/girepository-1.0/NM-1.0.typelib
%exclude /usr/lib32/girepository-1.0/NMClient-1.0.typelib
%exclude /usr/lib32/girepository-1.0/NetworkManager-1.0.typelib

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/network-online.target.wants/NetworkManager-wait-online.service

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/NetworkManager
%exclude /usr/bin/nm-online
%exclude /usr/libexec/nm-dhcp-helper
%exclude /usr/libexec/nm-dispatcher
%exclude /usr/libexec/nm-iface-helper

%files config
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/NetworkManager-dispatcher.service
%exclude /usr/lib/systemd/system/NetworkManager-wait-online.service
%exclude /usr/lib/systemd/system/NetworkManager.service
%exclude /usr/lib/systemd/system/network-online.target.wants/NetworkManager-wait-online.service
%exclude /usr/lib/udev/rules.d/84-nm-drivers.rules
%exclude /usr/lib/udev/rules.d/85-nm-unmanaged.rules

%files data
%defattr(-,root,root,-)
%exclude /usr/share/polkit-1/actions/org.freedesktop.NetworkManager.policy
/usr/share/dbus-1/system-services/org.freedesktop.NetworkManager.service
/usr/share/dbus-1/system-services/org.freedesktop.nm_dispatcher.service

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/NetworkManager/NetworkManager.h
%exclude /usr/include/NetworkManager/NetworkManagerVPN.h
%exclude /usr/include/NetworkManager/nm-connection.h
%exclude /usr/include/NetworkManager/nm-setting-8021x.h
%exclude /usr/include/NetworkManager/nm-setting-adsl.h
%exclude /usr/include/NetworkManager/nm-setting-bluetooth.h
%exclude /usr/include/NetworkManager/nm-setting-bond.h
%exclude /usr/include/NetworkManager/nm-setting-bridge-port.h
%exclude /usr/include/NetworkManager/nm-setting-bridge.h
%exclude /usr/include/NetworkManager/nm-setting-cdma.h
%exclude /usr/include/NetworkManager/nm-setting-connection.h
%exclude /usr/include/NetworkManager/nm-setting-dcb.h
%exclude /usr/include/NetworkManager/nm-setting-generic.h
%exclude /usr/include/NetworkManager/nm-setting-gsm.h
%exclude /usr/include/NetworkManager/nm-setting-infiniband.h
%exclude /usr/include/NetworkManager/nm-setting-ip4-config.h
%exclude /usr/include/NetworkManager/nm-setting-ip6-config.h
%exclude /usr/include/NetworkManager/nm-setting-olpc-mesh.h
%exclude /usr/include/NetworkManager/nm-setting-ppp.h
%exclude /usr/include/NetworkManager/nm-setting-pppoe.h
%exclude /usr/include/NetworkManager/nm-setting-serial.h
%exclude /usr/include/NetworkManager/nm-setting-team-port.h
%exclude /usr/include/NetworkManager/nm-setting-team.h
%exclude /usr/include/NetworkManager/nm-setting-vlan.h
%exclude /usr/include/NetworkManager/nm-setting-vpn.h
%exclude /usr/include/NetworkManager/nm-setting-wimax.h
%exclude /usr/include/NetworkManager/nm-setting-wired.h
%exclude /usr/include/NetworkManager/nm-setting-wireless-security.h
%exclude /usr/include/NetworkManager/nm-setting-wireless.h
%exclude /usr/include/NetworkManager/nm-setting.h
%exclude /usr/include/NetworkManager/nm-utils-enum-types.h
%exclude /usr/include/NetworkManager/nm-utils.h
%exclude /usr/include/NetworkManager/nm-version-macros.h
%exclude /usr/include/NetworkManager/nm-version.h
%exclude /usr/include/libnm-glib/libnm_glib.h
%exclude /usr/include/libnm-glib/nm-access-point.h
%exclude /usr/include/libnm-glib/nm-active-connection.h
%exclude /usr/include/libnm-glib/nm-client.h
%exclude /usr/include/libnm-glib/nm-device-adsl.h
%exclude /usr/include/libnm-glib/nm-device-bond.h
%exclude /usr/include/libnm-glib/nm-device-bridge.h
%exclude /usr/include/libnm-glib/nm-device-bt.h
%exclude /usr/include/libnm-glib/nm-device-ethernet.h
%exclude /usr/include/libnm-glib/nm-device-generic.h
%exclude /usr/include/libnm-glib/nm-device-infiniband.h
%exclude /usr/include/libnm-glib/nm-device-modem.h
%exclude /usr/include/libnm-glib/nm-device-olpc-mesh.h
%exclude /usr/include/libnm-glib/nm-device-team.h
%exclude /usr/include/libnm-glib/nm-device-vlan.h
%exclude /usr/include/libnm-glib/nm-device-wifi.h
%exclude /usr/include/libnm-glib/nm-device-wimax.h
%exclude /usr/include/libnm-glib/nm-device.h
%exclude /usr/include/libnm-glib/nm-dhcp4-config.h
%exclude /usr/include/libnm-glib/nm-dhcp6-config.h
%exclude /usr/include/libnm-glib/nm-glib-enum-types.h
%exclude /usr/include/libnm-glib/nm-ip4-config.h
%exclude /usr/include/libnm-glib/nm-ip6-config.h
%exclude /usr/include/libnm-glib/nm-object.h
%exclude /usr/include/libnm-glib/nm-remote-connection.h
%exclude /usr/include/libnm-glib/nm-remote-settings.h
%exclude /usr/include/libnm-glib/nm-secret-agent.h
%exclude /usr/include/libnm-glib/nm-types.h
%exclude /usr/include/libnm-glib/nm-vpn-connection.h
%exclude /usr/include/libnm-glib/nm-vpn-enum-types.h
%exclude /usr/include/libnm-glib/nm-vpn-plugin-ui-interface.h
%exclude /usr/include/libnm-glib/nm-vpn-plugin-utils.h
%exclude /usr/include/libnm-glib/nm-vpn-plugin.h
%exclude /usr/include/libnm-glib/nm-wimax-nsp.h
%exclude /usr/include/libnm/NetworkManager.h
%exclude /usr/include/libnm/nm-access-point.h
%exclude /usr/include/libnm/nm-active-connection.h
%exclude /usr/include/libnm/nm-client.h
%exclude /usr/include/libnm/nm-connection.h
%exclude /usr/include/libnm/nm-core-enum-types.h
%exclude /usr/include/libnm/nm-core-types.h
%exclude /usr/include/libnm/nm-dbus-interface.h
%exclude /usr/include/libnm/nm-device-adsl.h
%exclude /usr/include/libnm/nm-device-bond.h
%exclude /usr/include/libnm/nm-device-bridge.h
%exclude /usr/include/libnm/nm-device-bt.h
%exclude /usr/include/libnm/nm-device-ethernet.h
%exclude /usr/include/libnm/nm-device-generic.h
%exclude /usr/include/libnm/nm-device-infiniband.h
%exclude /usr/include/libnm/nm-device-ip-tunnel.h
%exclude /usr/include/libnm/nm-device-macvlan.h
%exclude /usr/include/libnm/nm-device-modem.h
%exclude /usr/include/libnm/nm-device-olpc-mesh.h
%exclude /usr/include/libnm/nm-device-team.h
%exclude /usr/include/libnm/nm-device-tun.h
%exclude /usr/include/libnm/nm-device-vlan.h
%exclude /usr/include/libnm/nm-device-vxlan.h
%exclude /usr/include/libnm/nm-device-wifi.h
%exclude /usr/include/libnm/nm-device-wimax.h
%exclude /usr/include/libnm/nm-device.h
%exclude /usr/include/libnm/nm-dhcp-config.h
%exclude /usr/include/libnm/nm-enum-types.h
%exclude /usr/include/libnm/nm-errors.h
%exclude /usr/include/libnm/nm-ip-config.h
%exclude /usr/include/libnm/nm-object.h
%exclude /usr/include/libnm/nm-remote-connection.h
%exclude /usr/include/libnm/nm-secret-agent-old.h
%exclude /usr/include/libnm/nm-setting-8021x.h
%exclude /usr/include/libnm/nm-setting-adsl.h
%exclude /usr/include/libnm/nm-setting-bluetooth.h
%exclude /usr/include/libnm/nm-setting-bond.h
%exclude /usr/include/libnm/nm-setting-bridge-port.h
%exclude /usr/include/libnm/nm-setting-bridge.h
%exclude /usr/include/libnm/nm-setting-cdma.h
%exclude /usr/include/libnm/nm-setting-connection.h
%exclude /usr/include/libnm/nm-setting-dcb.h
%exclude /usr/include/libnm/nm-setting-generic.h
%exclude /usr/include/libnm/nm-setting-gsm.h
%exclude /usr/include/libnm/nm-setting-infiniband.h
%exclude /usr/include/libnm/nm-setting-ip-config.h
%exclude /usr/include/libnm/nm-setting-ip-tunnel.h
%exclude /usr/include/libnm/nm-setting-ip4-config.h
%exclude /usr/include/libnm/nm-setting-ip6-config.h
%exclude /usr/include/libnm/nm-setting-macvlan.h
%exclude /usr/include/libnm/nm-setting-olpc-mesh.h
%exclude /usr/include/libnm/nm-setting-ppp.h
%exclude /usr/include/libnm/nm-setting-pppoe.h
%exclude /usr/include/libnm/nm-setting-serial.h
%exclude /usr/include/libnm/nm-setting-team-port.h
%exclude /usr/include/libnm/nm-setting-team.h
%exclude /usr/include/libnm/nm-setting-tun.h
%exclude /usr/include/libnm/nm-setting-vlan.h
%exclude /usr/include/libnm/nm-setting-vpn.h
%exclude /usr/include/libnm/nm-setting-vxlan.h
%exclude /usr/include/libnm/nm-setting-wimax.h
%exclude /usr/include/libnm/nm-setting-wired.h
%exclude /usr/include/libnm/nm-setting-wireless-security.h
%exclude /usr/include/libnm/nm-setting-wireless.h
%exclude /usr/include/libnm/nm-setting.h
%exclude /usr/include/libnm/nm-simple-connection.h
%exclude /usr/include/libnm/nm-types.h
%exclude /usr/include/libnm/nm-utils.h
%exclude /usr/include/libnm/nm-version-macros.h
%exclude /usr/include/libnm/nm-version.h
%exclude /usr/include/libnm/nm-vpn-connection.h
%exclude /usr/include/libnm/nm-vpn-dbus-interface.h
%exclude /usr/include/libnm/nm-vpn-editor-plugin.h
%exclude /usr/include/libnm/nm-vpn-editor.h
%exclude /usr/include/libnm/nm-vpn-plugin-info.h
%exclude /usr/include/libnm/nm-vpn-plugin-old.h
%exclude /usr/include/libnm/nm-vpn-service-plugin.h
%exclude /usr/include/libnm/nm-wimax-nsp.h
%exclude /usr/lib64/girepository-1.0/NM-1.0.typelib
%exclude /usr/lib64/girepository-1.0/NMClient-1.0.typelib
%exclude /usr/lib64/girepository-1.0/NetworkManager-1.0.typelib
%exclude /usr/lib64/libnm-glib-vpn.so
%exclude /usr/lib64/pkgconfig/NetworkManager.pc
%exclude /usr/lib64/pkgconfig/libnm-glib-vpn.pc
%exclude /usr/lib64/pkgconfig/libnm-glib.pc
%exclude /usr/lib64/pkgconfig/libnm-util.pc
%exclude /usr/lib64/pkgconfig/libnm.pc
%exclude /usr/share/gir-1.0/NM-1.0.gir
%exclude /usr/share/gir-1.0/NMClient-1.0.gir
%exclude /usr/share/gir-1.0/NetworkManager-1.0.gir
/usr/lib64/libnm-glib.so
/usr/lib64/libnm-util.so
/usr/lib64/libnm.so

%files dev32
%defattr(-,root,root,-)
%exclude /usr/lib32/libnm-glib-vpn.so
%exclude /usr/lib32/pkgconfig/32NetworkManager.pc
%exclude /usr/lib32/pkgconfig/32libnm-glib-vpn.pc
%exclude /usr/lib32/pkgconfig/32libnm-glib.pc
%exclude /usr/lib32/pkgconfig/32libnm-util.pc
%exclude /usr/lib32/pkgconfig/32libnm.pc
%exclude /usr/lib32/pkgconfig/NetworkManager.pc
%exclude /usr/lib32/pkgconfig/libnm-glib-vpn.pc
%exclude /usr/lib32/pkgconfig/libnm-glib.pc
%exclude /usr/lib32/pkgconfig/libnm-util.pc
%exclude /usr/lib32/pkgconfig/libnm.pc
/usr/lib32/libnm-glib.so
/usr/lib32/libnm-util.so
/usr/lib32/libnm.so

%files doc
%defattr(-,root,root,-)
%exclude /usr/share/doc/NetworkManager/examples/server.conf
%exclude /usr/share/gtk-doc/html/NetworkManager/NetworkManager.conf.html
%exclude /usr/share/gtk-doc/html/NetworkManager/NetworkManager.devhelp2
%exclude /usr/share/gtk-doc/html/NetworkManager/NetworkManager.html
%exclude /usr/share/gtk-doc/html/NetworkManager/dbus-types.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.AccessPoint.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.AgentManager.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Connection.Active.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.DHCP4Config.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.DHCP6Config.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.Adsl.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.Bluetooth.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.Bond.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.Bridge.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.Generic.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.IPTunnel.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.Infiniband.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.Macvlan.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.Modem.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.OlpcMesh.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.Statistics.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.Team.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.Tun.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.Veth.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.Vlan.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.Vxlan.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.WiMax.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.Wired.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.Wireless.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Device.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.IP4Config.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.IP6Config.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.PPP.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.SecretAgent.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Settings.Connection.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.Settings.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.VPN.Connection.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.VPN.Plugin.html
%exclude /usr/share/gtk-doc/html/NetworkManager/gdbus-org.freedesktop.NetworkManager.html
%exclude /usr/share/gtk-doc/html/NetworkManager/home.png
%exclude /usr/share/gtk-doc/html/NetworkManager/index.html
%exclude /usr/share/gtk-doc/html/NetworkManager/ix01.html
%exclude /usr/share/gtk-doc/html/NetworkManager/left-insensitive.png
%exclude /usr/share/gtk-doc/html/NetworkManager/left.png
%exclude /usr/share/gtk-doc/html/NetworkManager/license.html
%exclude /usr/share/gtk-doc/html/NetworkManager/manpages.html
%exclude /usr/share/gtk-doc/html/NetworkManager/nm-dbus-types.html
%exclude /usr/share/gtk-doc/html/NetworkManager/nm-online.html
%exclude /usr/share/gtk-doc/html/NetworkManager/nm-settings-ifcfg-rh.html
%exclude /usr/share/gtk-doc/html/NetworkManager/nm-settings-keyfile.html
%exclude /usr/share/gtk-doc/html/NetworkManager/nm-settings.html
%exclude /usr/share/gtk-doc/html/NetworkManager/nm-vpn-dbus-types.html
%exclude /usr/share/gtk-doc/html/NetworkManager/nmcli-examples.html
%exclude /usr/share/gtk-doc/html/NetworkManager/nmcli.html
%exclude /usr/share/gtk-doc/html/NetworkManager/nmtui.html
%exclude /usr/share/gtk-doc/html/NetworkManager/ref-settings.html
%exclude /usr/share/gtk-doc/html/NetworkManager/right-insensitive.png
%exclude /usr/share/gtk-doc/html/NetworkManager/right.png
%exclude /usr/share/gtk-doc/html/NetworkManager/secrets-flags.html
%exclude /usr/share/gtk-doc/html/NetworkManager/spec.html
%exclude /usr/share/gtk-doc/html/NetworkManager/style.css
%exclude /usr/share/gtk-doc/html/NetworkManager/up-insensitive.png
%exclude /usr/share/gtk-doc/html/NetworkManager/up.png
%exclude /usr/share/gtk-doc/html/libnm-glib/NMAccessPoint.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMActiveConnection.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMClient.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMDHCP4Config.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMDHCP6Config.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMDevice.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMDeviceAdsl.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMDeviceBond.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMDeviceBridge.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMDeviceBt.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMDeviceEthernet.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMDeviceGeneric.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMDeviceInfiniband.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMDeviceModem.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMDeviceOlpcMesh.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMDeviceTeam.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMDeviceVlan.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMDeviceWifi.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMDeviceWimax.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMIP4Config.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMIP6Config.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMObject.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMRemoteConnection.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMRemoteSettings.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMSecretAgent.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMVPNConnection.html
%exclude /usr/share/gtk-doc/html/libnm-glib/NMWimaxNsp.html
%exclude /usr/share/gtk-doc/html/libnm-glib/annotation-glossary.html
%exclude /usr/share/gtk-doc/html/libnm-glib/api-index-full.html
%exclude /usr/share/gtk-doc/html/libnm-glib/ch02.html
%exclude /usr/share/gtk-doc/html/libnm-glib/home.png
%exclude /usr/share/gtk-doc/html/libnm-glib/index.html
%exclude /usr/share/gtk-doc/html/libnm-glib/left-insensitive.png
%exclude /usr/share/gtk-doc/html/libnm-glib/left.png
%exclude /usr/share/gtk-doc/html/libnm-glib/libnm-glib-NMVPNPlugin.html
%exclude /usr/share/gtk-doc/html/libnm-glib/libnm-glib-NMVpnPluginUiWidget.html
%exclude /usr/share/gtk-doc/html/libnm-glib/libnm-glib-nm-types.html
%exclude /usr/share/gtk-doc/html/libnm-glib/libnm-glib-nm-vpn-plugin-utils.html
%exclude /usr/share/gtk-doc/html/libnm-glib/libnm-glib.devhelp2
%exclude /usr/share/gtk-doc/html/libnm-glib/libnm-glib.png
%exclude /usr/share/gtk-doc/html/libnm-glib/object-tree.html
%exclude /usr/share/gtk-doc/html/libnm-glib/ref-overview.html
%exclude /usr/share/gtk-doc/html/libnm-glib/right-insensitive.png
%exclude /usr/share/gtk-doc/html/libnm-glib/right.png
%exclude /usr/share/gtk-doc/html/libnm-glib/style.css
%exclude /usr/share/gtk-doc/html/libnm-glib/up-insensitive.png
%exclude /usr/share/gtk-doc/html/libnm-glib/up.png
%exclude /usr/share/gtk-doc/html/libnm-util/NMConnection.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSetting.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSetting8021x.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingAdsl.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingBluetooth.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingBond.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingBridge.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingBridgePort.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingCdma.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingConnection.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingDcb.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingGeneric.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingGsm.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingIP4Config.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingIP6Config.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingInfiniband.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingOlpcMesh.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingPPP.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingPPPOE.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingSerial.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingTeam.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingTeamPort.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingVPN.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingVlan.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingWimax.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingWired.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingWireless.html
%exclude /usr/share/gtk-doc/html/libnm-util/NMSettingWirelessSecurity.html
%exclude /usr/share/gtk-doc/html/libnm-util/annotation-glossary.html
%exclude /usr/share/gtk-doc/html/libnm-util/api-index-full.html
%exclude /usr/share/gtk-doc/html/libnm-util/ch01.html
%exclude /usr/share/gtk-doc/html/libnm-util/home.png
%exclude /usr/share/gtk-doc/html/libnm-util/index.html
%exclude /usr/share/gtk-doc/html/libnm-util/left-insensitive.png
%exclude /usr/share/gtk-doc/html/libnm-util/left.png
%exclude /usr/share/gtk-doc/html/libnm-util/libnm-util-NetworkManager.html
%exclude /usr/share/gtk-doc/html/libnm-util/libnm-util-NetworkManagerVPN.html
%exclude /usr/share/gtk-doc/html/libnm-util/libnm-util-nm-utils.html
%exclude /usr/share/gtk-doc/html/libnm-util/libnm-util.devhelp2
%exclude /usr/share/gtk-doc/html/libnm-util/object-tree.html
%exclude /usr/share/gtk-doc/html/libnm-util/right-insensitive.png
%exclude /usr/share/gtk-doc/html/libnm-util/right.png
%exclude /usr/share/gtk-doc/html/libnm-util/style.css
%exclude /usr/share/gtk-doc/html/libnm-util/up-insensitive.png
%exclude /usr/share/gtk-doc/html/libnm-util/up.png
%exclude /usr/share/gtk-doc/html/libnm/NMAccessPoint.html
%exclude /usr/share/gtk-doc/html/libnm/NMActiveConnection.html
%exclude /usr/share/gtk-doc/html/libnm/NMClient.html
%exclude /usr/share/gtk-doc/html/libnm/NMConnection.html
%exclude /usr/share/gtk-doc/html/libnm/NMDevice.html
%exclude /usr/share/gtk-doc/html/libnm/NMDeviceAdsl.html
%exclude /usr/share/gtk-doc/html/libnm/NMDeviceBond.html
%exclude /usr/share/gtk-doc/html/libnm/NMDeviceBridge.html
%exclude /usr/share/gtk-doc/html/libnm/NMDeviceBt.html
%exclude /usr/share/gtk-doc/html/libnm/NMDeviceEthernet.html
%exclude /usr/share/gtk-doc/html/libnm/NMDeviceGeneric.html
%exclude /usr/share/gtk-doc/html/libnm/NMDeviceIPTunnel.html
%exclude /usr/share/gtk-doc/html/libnm/NMDeviceInfiniband.html
%exclude /usr/share/gtk-doc/html/libnm/NMDeviceMacvlan.html
%exclude /usr/share/gtk-doc/html/libnm/NMDeviceModem.html
%exclude /usr/share/gtk-doc/html/libnm/NMDeviceOlpcMesh.html
%exclude /usr/share/gtk-doc/html/libnm/NMDeviceTeam.html
%exclude /usr/share/gtk-doc/html/libnm/NMDeviceTun.html
%exclude /usr/share/gtk-doc/html/libnm/NMDeviceVlan.html
%exclude /usr/share/gtk-doc/html/libnm/NMDeviceVxlan.html
%exclude /usr/share/gtk-doc/html/libnm/NMDeviceWifi.html
%exclude /usr/share/gtk-doc/html/libnm/NMDeviceWimax.html
%exclude /usr/share/gtk-doc/html/libnm/NMDhcpConfig.html
%exclude /usr/share/gtk-doc/html/libnm/NMIPConfig.html
%exclude /usr/share/gtk-doc/html/libnm/NMObject.html
%exclude /usr/share/gtk-doc/html/libnm/NMRemoteConnection.html
%exclude /usr/share/gtk-doc/html/libnm/NMSecretAgentOld.html
%exclude /usr/share/gtk-doc/html/libnm/NMSetting.html
%exclude /usr/share/gtk-doc/html/libnm/NMSetting8021x.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingAdsl.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingBluetooth.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingBond.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingBridge.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingBridgePort.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingCdma.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingConnection.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingDcb.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingGeneric.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingGsm.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingIP4Config.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingIP6Config.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingIPConfig.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingIPTunnel.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingInfiniband.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingMacvlan.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingOlpcMesh.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingPpp.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingPppoe.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingSerial.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingTeam.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingTeamPort.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingTun.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingVlan.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingVpn.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingVxlan.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingWimax.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingWired.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingWireless.html
%exclude /usr/share/gtk-doc/html/libnm/NMSettingWirelessSecurity.html
%exclude /usr/share/gtk-doc/html/libnm/NMSimpleConnection.html
%exclude /usr/share/gtk-doc/html/libnm/NMVpnConnection.html
%exclude /usr/share/gtk-doc/html/libnm/NMVpnEditorPlugin.html
%exclude /usr/share/gtk-doc/html/libnm/NMWimaxNsp.html
%exclude /usr/share/gtk-doc/html/libnm/annotation-glossary.html
%exclude /usr/share/gtk-doc/html/libnm/api-index-full.html
%exclude /usr/share/gtk-doc/html/libnm/ch02.html
%exclude /usr/share/gtk-doc/html/libnm/ch03.html
%exclude /usr/share/gtk-doc/html/libnm/ch04.html
%exclude /usr/share/gtk-doc/html/libnm/ch05.html
%exclude /usr/share/gtk-doc/html/libnm/ch06.html
%exclude /usr/share/gtk-doc/html/libnm/home.png
%exclude /usr/share/gtk-doc/html/libnm/index.html
%exclude /usr/share/gtk-doc/html/libnm/left-insensitive.png
%exclude /usr/share/gtk-doc/html/libnm/left.png
%exclude /usr/share/gtk-doc/html/libnm/libnm-nm-dbus-interface.html
%exclude /usr/share/gtk-doc/html/libnm/libnm-nm-errors.html
%exclude /usr/share/gtk-doc/html/libnm/libnm-nm-utils.html
%exclude /usr/share/gtk-doc/html/libnm/libnm-nm-version.html
%exclude /usr/share/gtk-doc/html/libnm/libnm-nm-vpn-dbus-interface.html
%exclude /usr/share/gtk-doc/html/libnm/libnm.devhelp2
%exclude /usr/share/gtk-doc/html/libnm/libnm.png
%exclude /usr/share/gtk-doc/html/libnm/object-tree.html
%exclude /usr/share/gtk-doc/html/libnm/ref-overview.html
%exclude /usr/share/gtk-doc/html/libnm/right-insensitive.png
%exclude /usr/share/gtk-doc/html/libnm/right.png
%exclude /usr/share/gtk-doc/html/libnm/style.css
%exclude /usr/share/gtk-doc/html/libnm/up-insensitive.png
%exclude /usr/share/gtk-doc/html/libnm/up.png
%exclude /usr/share/man/man1/nm-online.1
%exclude /usr/share/man/man1/nmcli.1
%exclude /usr/share/man/man1/nmtui-connect.1
%exclude /usr/share/man/man1/nmtui-edit.1
%exclude /usr/share/man/man1/nmtui-hostname.1
%exclude /usr/share/man/man1/nmtui.1
%exclude /usr/share/man/man5/NetworkManager.conf.5
%exclude /usr/share/man/man5/nm-settings-keyfile.5
%exclude /usr/share/man/man5/nm-settings.5
%exclude /usr/share/man/man5/nm-system-settings.conf.5
%exclude /usr/share/man/man7/nmcli-examples.7
%exclude /usr/share/man/man8/NetworkManager.8

%files lib
%defattr(-,root,root,-)
%exclude /usr/lib64/NetworkManager/libnm-device-plugin-adsl.so
%exclude /usr/lib64/NetworkManager/libnm-settings-plugin-ibft.so
%exclude /usr/lib64/libnm-glib-vpn.so.1
%exclude /usr/lib64/libnm-glib-vpn.so.1.2.0
/usr/lib64/libnm-glib.so.4
/usr/lib64/libnm-glib.so.4.9.0
/usr/lib64/libnm-util.so.2
/usr/lib64/libnm-util.so.2.7.0
/usr/lib64/libnm.so.0
/usr/lib64/libnm.so.0.1.0

%files lib32
%defattr(-,root,root,-)
%exclude /usr/lib32/libnm-glib-vpn.so.1
%exclude /usr/lib32/libnm-glib-vpn.so.1.2.0
/usr/lib32/libnm-glib.so.4
/usr/lib32/libnm-glib.so.4.9.0
/usr/lib32/libnm-util.so.2
/usr/lib32/libnm-util.so.2.7.0
/usr/lib32/libnm.so.0
/usr/lib32/libnm.so.0.1.0

%files locales -f NetworkManager.lang
%defattr(-,root,root,-)

